/* Additive pedagogical UX: keeps existing UI/renderers intact. */
(function(){
const KEY='cyberlab_ux_v1_';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const aid=()=>window.CyberAccounts?.activeId||'default';
const state=()=>{try{return Object.assign({completed:{},reviews:[],labs:{},onboarding:false,start:null},JSON.parse(localStorage.getItem(KEY+aid())||'{}'));}catch{return {completed:{},reviews:[],labs:{},onboarding:false,start:null};}};
const save=s=>localStorage.setItem(KEY+aid(),JSON.stringify(s));
function fragments(text){const out=[];String(text||'').split(/\n\s*\n/).filter(Boolean).forEach(b=>{if(b.length<=700)out.push(b.trim());else{let r=b.trim();while(r.length>700){let p=r.slice(0,700).lastIndexOf('. ');p=p>300?p+1:700;out.push(r.slice(0,p).trim());r=r.slice(p).trim();}if(r)out.push(r);}});return out.length?out:['Contenido teórico'];}
class Reader{constructor(){this.c=null;this.i=0;this.a={};}
 open(id){for(const m of window.CyberData?.modules||[]){const c=(m.concepts||[]).find(x=>x.id===id);if(c){this.c={c,m,steps:this.build(c)};this.i=0;this.a={};this.render();return;}}}
 build(c){const s=[];fragments(c.theory).forEach((t,i)=>{s.push({k:'t',title:`Teoría · ${i+1}`,html:`<div>${esc(t).replace(/\n/g,'<br>')}</div>`});s.push({k:'q',q:{id:`${c.id}-q${i}`,prompt:'¿Qué idea principal presenta este bloque?',options:[c.summary||'La idea central del concepto.','Una conclusión que no aparece en la lección.','Un procedimiento sin relación con el concepto.'],answer:0,why:`La respuesta correcta coincide con la idea central explicada: ${c.summary||'revisa el bloque anterior.'}`}});});
 if(c.example)s.push({k:'box',title:'💡 Ejemplo aplicado',html:`<div class="ux-reader-callout example"><strong>Ejemplo</strong><p>${esc(c.example)}</p></div>`});
 if(c.practice)s.push({k:'box',title:'🧪 Práctica mental',html:`<div class="ux-reader-callout practice"><strong>Práctica</strong><p>${esc(c.practice)}</p></div>`});
 if(c.defense)s.push({k:'box',title:'🛡️ Cómo defender',html:`<div class="ux-reader-callout defense"><strong>Defensa</strong><p>${esc(c.defense)}</p></div>`});
 if(c.detection)s.push({k:'box',title:'🔍 Cómo detectar',html:`<div class="ux-reader-callout detection"><strong>Detección</strong><p>${esc(c.detection)}</p></div>`});return s;}
 render(){if(!this.c)return;let o=document.getElementById('ux-reader');if(!o){o=document.createElement('div');o.id='ux-reader';o.className='ux-reader-overlay';document.body.appendChild(o);}const s=this.c.steps[this.i],p=Math.round((this.i+1)/this.c.steps.length*100),q=s.k==='q'?s.q:null;o.innerHTML=`<div class="ux-reader-card"><div class="ux-reader-top"><button id="ux-x">← Volver</button><span>${p}%</span></div><div class="ux-reader-progress"><i style="width:${p}%"></i></div><div class="ux-reader-context"><span>${esc(this.c.m.title)}</span><small>${this.i+1}/${this.c.steps.length}</small></div><h2>${esc(s.title||'Comprueba lo aprendido')}</h2><div class="ux-reader-content">${s.html||this.question(q)}</div><div class="ux-reader-actions">${this.i?'<button class="btn btn-secondary" id="ux-prev">Atrás</button>':'<span></span>'}<button class="btn btn-primary" id="ux-next">${this.i===this.c.steps.length-1?'Completar lección':'Siguiente →'}</button></div></div>`;o.querySelector('#ux-x').onclick=()=>o.remove();o.querySelector('#ux-prev')?.addEventListener('click',()=>{this.i--;this.render();});o.querySelector('#ux-next').onclick=()=>this.next();o.querySelectorAll('[data-ans]').forEach(b=>b.onclick=()=>this.answer(Number(b.dataset.ans),q));}
 question(q){const a=this.a[q.id];return `<div class="ux-question"><h3>🧠 ${esc(q.prompt)}</h3><div class="ux-question-options">${q.options.map((x,i)=>`<button class="ux-question-option ${a!==undefined?(i===q.answer?'correct':i===a?'incorrect':''):''}" data-ans="${i}" ${a!==undefined?'disabled':''}>${esc(x)}</button>`).join('')}</div>${a!==undefined?`<div class="ux-feedback ${a===q.answer?'correct':'incorrect'}"><strong>${a===q.answer?'✅ Correcto':'❌ Incorrecto'}</strong><p>${esc(q.why)}</p></div>`:''}</div>`;}
 answer(i,q){this.a[q.id]=i;this.render();}
 next(){const s=this.c.steps[this.i];if(s.k==='q'&&this.a[s.q.id]===undefined)return;if(this.i<this.c.steps.length-1){this.i++;this.render();return;}this.complete();}
 complete(){const s=state(),id=this.c.c.id,qs=this.c.steps.filter(x=>x.k==='q').map(x=>x.q),correct=qs.filter(q=>this.a[q.id]===q.answer).length;s.completed[id]={done:true,mastered:correct===qs.length,correct,total:qs.length};s.reviews=s.reviews||[];qs.forEach(q=>{if(!s.reviews.some(x=>x.key===q.id))s.reviews.push({key:q.id,prompt:q.prompt,options:q.options,answer:q.answer,why:q.why,due:Date.now()+86400000,i:0});});save(s);if(window.CyberGamification){window.CyberGamification.addXP(60,'Lectura completa',`ux-read-${id}`);qs.forEach(q=>{if(this.a[q.id]===q.answer)window.CyberGamification.addXP(12,'Pregunta de refuerzo',`ux-q-${q.id}`);});}this.c=null;document.getElementById('ux-reader')?.remove();const o=document.createElement('div');o.className='ux-celebration';o.innerHTML=`<div class="ux-celebration-card"><div class="emoji">${correct===qs.length?'👑':'🎉'}</div><span class="tag cyan">LECCIÓN COMPLETADA</span><h2>${esc(this.c?.c?.name||'Concepto aprendido')}</h2><p>${correct===qs.length?'Dominaste la lección y acertaste todas las preguntas de refuerzo.':'Terminaste toda la teoría. Las preguntas falladas volverán en el repaso espaciado.'}</p><div class="ux-xp-chip">+${60+correct*12} XP</div><br><button class="btn btn-primary" id="ux-ok">Continuar</button></div>`;document.body.appendChild(o);o.querySelector('#ux-ok').onclick=()=>o.remove();setTimeout(()=>o.remove(),9000);refresh();}
}
function decorateLessons(){document.querySelectorAll('#learning-tree-root .accordion-content > div').forEach(card=>{if(card.dataset.ux)return;const b=card.querySelector('.mastery-btn[onclick*="setMastery"]');const m=b?.getAttribute('onclick')?.match(/setMastery\(['\"]([^'\"]+)/);if(!m)return;card.dataset.ux='1';const x=document.createElement('button');x.className='ux-study-launch';x.textContent='📖 Estudiar en pasos';x.onclick=()=>window.CyberLesson.open(m[1]);card.appendChild(x);});}
function route(target){if(!target)return;const mods=window.CyberData?.modules||[],s=state(),done=new Set(window.CyberStorage?.data?.completedModules||[]);const status=m=>done.has(m.id)?((m.concepts||[]).every(c=>s.completed[c.id]?.mastered)?'mastered':'completed'):(m.prerequisites||[]).some(x=>!done.has(x))?'locked':'available';target.innerHTML=`<div class="ux-route-head"><div><span style="font-size:.68rem;color:var(--text-muted)">RUTA UNIFICADA</span><h3>Tu camino de aprendizaje</h3></div><span>${mods.filter(m=>status(m)!=='locked').length}/${mods.length}</span></div><div class="ux-route-track">${mods.map((m,i)=>{const st=status(m),ic=st==='mastered'?'👑':st==='completed'?'✓':st==='locked'?'🔒':m.icon||'▶';return `<button class="ux-route-node ${st}" data-route="${esc(m.id)}" ${st==='locked'?'disabled':''}><span class="ux-route-node-circle">${ic}</span><strong>${esc(m.title)}</strong><small>${st==='locked'?'Bloqueado':st==='mastered'?'Dominado':st==='completed'?'Completado':'Disponible'}</small></button>${i<mods.length-1?'<span class="ux-route-line"></span>':''}`}).join('')}</div>`;target.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>location.hash='#tree');}
function ensureRoutes(){const d=document.querySelector('#view-dashboard .card[style*="margin-bottom"]'),t=document.getElementById('learning-tree-root');if(d&&!document.getElementById('ux-route-dash')){const r=document.createElement('div');r.id='ux-route-dash';r.className='ux-route';d.after(r);}if(t&&!document.getElementById('ux-route-tree')){const r=document.createElement('div');r.id='ux-route-tree';r.className='ux-route';t.prepend(r);}route(document.getElementById('ux-route-dash'));route(document.getElementById('ux-route-tree'));}
function labs(){const list=window.CyberData?.labs||[],s=state();document.querySelectorAll('#labs-root > .card').forEach(card=>{if(card.querySelector('.ux-lab-checklist'))return;const title=card.querySelector('h3')?.textContent||'',lab=list.find(x=>title.includes(x.title));if(!lab)return;const vals=s.labs[lab.id]||{};const box=document.createElement('div');box.className='ux-lab-checklist';const count=lab.steps.filter((_,i)=>vals[i]).length;box.innerHTML=`<div class="ux-lab-checklist-head"><strong>✅ Checklist de ejecución</strong><span>${count}/${lab.steps.length}</span></div><div class="ux-lab-progress"><i style="width:${lab.steps.length?count/lab.steps.length*100:0}%"></i></div>${lab.steps.map((st,i)=>`<label class="ux-lab-step ${vals[i]?'checked':''}"><input type="checkbox" data-ls="${i}" ${vals[i]?'checked':''}><span><strong>Paso ${st.step}: ${esc(st.title)}</strong><br>${esc(st.description)}</span></label>`).join('')}`;const h=[...card.querySelectorAll('h4')].find(x=>x.textContent.includes('Pasos Guiados'));(h||card.firstElementChild).after(box);box.querySelectorAll('[data-ls]').forEach(i=>i.onchange=()=>{const x=state();x.labs[lab.id]=x.labs[lab.id]||{};x.labs[lab.id][i.dataset.ls]=i.checked;save(x);i.parentElement.classList.toggle('checked',i.checked);const n=[...box.querySelectorAll('[data-ls]')].filter(y=>y.checked).length;box.querySelector('.ux-lab-checklist-head span').textContent=`${n}/${lab.steps.length}`;box.querySelector('.ux-lab-progress i').style.width=`${lab.steps.length?n/lab.steps.length*100:0}%`;});});}
function reviews(){const root=document.getElementById('spaced-repetition-root');if(!root)return;root.querySelector('#ux-review')?.remove();const s=state(),q=(s.reviews||[]).find(x=>x.due<=Date.now());if(!q)return;const p=document.createElement('div');p.id='ux-review';p.className='card ux-review-panel';p.innerHTML=`<span class="tag purple">🧠 REPASO RÁPIDO</span><h3>${esc(q.prompt)}</h3><div class="ux-review-options">${q.options.map((x,i)=>`<button class="quiz-option-btn" data-r="${i}">${esc(x)}</button>`).join('')}</div><div id="ux-rf"></div>`;root.prepend(p);p.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{const i=+b.dataset.r,ok=i===q.answer;p.querySelectorAll('button').forEach(x=>x.disabled=true);p.querySelectorAll('button')[q.answer].classList.add('correct');if(!ok)b.classList.add('incorrect');p.querySelector('#ux-rf').textContent=ok?'✅ Correcto.':'❌ La explicación volverá a aparecer pronto.';if(ok)window.CyberGamification?.addXP(8,'Repaso rápido',`ux-review-${q.key}-${q.i}`);const x=state(),item=x.reviews.find(z=>z.key===q.key);if(item){item.i=Math.min((item.i||0)+1,4);item.due=Date.now()+[1,3,7,14,30][item.i]*86400000;save(x);}});}
function header(){const h=document.querySelector('.header-right');if(!h||h.querySelector('.ux-streak-badge'))return;const d=window.CyberStorage?.data||{};const a=document.createElement('span');a.className='ux-streak-badge';a.innerHTML=`🔥 <b>${d.streak||1}</b>`;const b=document.createElement('span');b.className='ux-achievement-badge';b.innerHTML=`🏆 <b>${(d.unlockedAchievements||[]).length}</b>`;h.prepend(b,a);}
function onboarding(){const s=state();if(s.onboarding||!window.CyberAccounts?.activeId)return;const qs=[['¿Qué representa CIA?',['Confidencialidad, Integridad y Disponibilidad','Código, Internet y Antivirus'],0],['¿Qué comando muestra procesos en Linux?',['top','chmod'],0],['¿Qué herramienta analiza tráfico capturado?',['Wireshark','PowerPoint'],0]];let i=0,score=0;const o=document.createElement('div');o.className='ux-onboarding';document.body.appendChild(o);const draw=()=>{const q=qs[i];o.innerHTML=`<div class="ux-onboarding-card"><span class="tag cyan">BIENVENIDO A CYBERLAB</span><h2>Ubica tu punto de partida</h2><p>Es opcional. Puedes empezar desde cero.</p><div class="ux-onboarding-progress"><i style="width:${i/qs.length*100}%"></i></div><strong>Pregunta ${i+1} de ${qs.length}</strong><h3>${esc(q[0])}</h3><div class="ux-onboarding-options">${q[1].map((x,j)=>`<button class="btn btn-secondary" data-o="${j}">${esc(x)}</button>`).join('')}</div><div class="ux-onboarding-actions"><button id="ux-zero" class="btn btn-secondary">Empezar desde cero</button></div></div>`;o.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{if(+b.dataset.o===q[2])score++;i++;i<qs.length?draw():finish();});o.querySelector('#ux-zero').onclick=()=>{score=0;finish();};};const finish=()=>{const x=state();x.onboarding=true;x.start=(window.CyberData?.modules||[])[Math.min(score,(window.CyberData?.modules||[]).length-1)]?.id;save(x);o.remove();refresh();};draw();}
function refresh(){setTimeout(()=>{decorateLessons();ensureRoutes();labs();reviews();header();},250);}
function init(){const l=document.createElement('link');l.rel='stylesheet';l.href='./css/gamification-ux.css?v=1';document.head.appendChild(l);window.CyberLesson=new Reader();window.CyberLearningPath={renderAll:ensureRoutes};refresh();setTimeout(onboarding,800);window.addEventListener('hashchange',refresh);window.addEventListener('cyberlab_state_updated',refresh);window.addEventListener('cyberlab_account_changed',()=>setTimeout(onboarding,400));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
