/* CyberLab Notes Manager — safe text rendering */
class NotesEngine{
 constructor(){this.storage=window.CyberStorage;}
 esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 render(){const notes=this.storage.data.notes||[],c=document.getElementById('notes-root');if(!c)return;c.innerHTML='';const h=document.createElement('div');h.className='card';h.style.marginBottom='20px';h.innerHTML=`<div class="card-header"><h3>Gestor de Apuntes Personales (${notes.length})</h3><button class="btn btn-primary" onclick="CyberNotes.openNewNoteModal()">+ Nueva Nota</button></div><div style="display:flex;gap:12px;margin-top:14px"><button class="btn btn-secondary" onclick="CyberNotes.filterNotes('all')">Todas</button><button class="btn btn-secondary" onclick="CyberNotes.filterNotes('notUnderstood')">⚠️ No entiendo (${notes.filter(n=>n.notUnderstood).length})</button></div>`;c.appendChild(h);const g=document.createElement('div');g.className='grid-cards';g.id='notes-grid';c.appendChild(g);this.renderNotesList(notes);}
 renderNotesList(list){const g=document.getElementById('notes-grid');if(!g)return;g.innerHTML='';list.forEach(n=>{const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-header"><span class="tag ${n.notUnderstood?'red':'cyan'}">${n.notUnderstood?'⚠️ No Entendido':this.esc(n.area)}</span><button class="btn-icon" style="width:28px;height:28px" onclick="CyberNotes.deleteNote('${this.esc(n.id)}')">✕</button></div><h4>${this.esc(n.title)}</h4><p style="color:var(--text-muted);white-space:pre-line">${this.esc(n.content)}</p><div style="display:flex;gap:6px;flex-wrap:wrap">${(n.tags||[]).map(t=>`<span class="tag purple">#${this.esc(t)}</span>`).join('')}</div>`;g.appendChild(card);});}
 filterNotes(f){const n=this.storage.data.notes||[];this.renderNotesList(f==='notUnderstood'?n.filter(x=>x.notUnderstood):n);}
 openNewNoteModal(){document.getElementById('note-modal')?.classList.add('active');}
 saveNewNote(){const title=document.getElementById('note-title-input').value.trim(),area=document.getElementById('note-area-input').value.trim(),tags=document.getElementById('note-tags-input').value.trim(),content=document.getElementById('note-content-input').value.trim(),nu=document.getElementById('note-not-understood-check').checked;if(!title||!content){alert('Ingresa título y contenido.');return;}this.storage.data.notes.push({id:`note-${Date.now()}`,title,area:area||'General',tags:tags?tags.split(',').map(t=>t.trim()).filter(Boolean):['Notas'],content,notUnderstood:nu,createdAt:new Date().toISOString()});this.storage.saveData();window.CyberGamification.addXP(10,'Nota guardada');document.getElementById('note-modal')?.classList.remove('active');['note-title-input','note-content-input'].forEach(id=>{const e=document.getElementById(id);if(e)e.value='';});this.render();}
 deleteNote(id){if(confirm('¿Eliminar esta nota?')){this.storage.data.notes=this.storage.data.notes.filter(n=>n.id!==id);this.storage.saveData();this.render();}}
}
window.CyberNotes=new NotesEngine();
