/* Active local account profile UI. */
(function(){
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  async function importFile(input){const file=input.files?.[0];if(!file)return;try{window.CyberStorage.importBackup(await file.text());}finally{input.value='';}}
  function render(){const c=document.getElementById('profile-root'),a=window.CyberAccounts?.getActive(),d=window.CyberStorage?.data;if(!c||!a||!d)return;const ach=window.CyberData?.achievements||[];c.innerHTML=`
  <div class="card" style="margin-bottom:20px"><div style="display:flex;align-items:center;gap:16px;flex-wrap:wrap">
   ${a.avatar?`<img src="${a.avatar}" alt="Foto de ${esc(a.username)}" style="width:88px;height:88px;object-fit:cover;border-radius:50%;border:3px solid var(--accent-cyan)">`:'<div style="width:88px;height:88px;border-radius:50%;display:grid;place-items:center;font-size:3rem;background:var(--bg-surface)">👤</div>'}
   <div style="flex:1"><h2>${esc(a.username)}</h2><p style="color:var(--text-muted);margin:4px 0 8px">${esc(a.bio||'Perfil de estudiante de CyberLab')}</p><div style="display:flex;gap:8px;flex-wrap:wrap"><span class="tag cyan">Nivel ${d.level}</span><span class="tag purple">${d.xp.toLocaleString()} XP</span><span class="tag yellow">🔥 ${d.streak} días</span></div></div>
   <div style="display:flex;gap:8px;flex-wrap:wrap"><button id="edit-account" class="btn btn-secondary">✏️ Editar</button><button id="switch-account" class="btn btn-secondary">👥 Cambiar usuario</button><button id="logout-account" class="btn btn-primary">Salir</button></div>
  </div></div>
  <div class="grid-cards"><div class="card"><h3>Objetivos</h3><p><strong>Principal:</strong> ${esc(d.primaryObjective)}</p><p><strong>Secundario:</strong> ${esc(d.secondaryObjective)}</p></div>
  <div class="card"><h3>Copia de Seguridad</h3><p style="color:var(--text-muted)">El progreso pertenece a ${esc(a.username)}.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn btn-primary" onclick="CyberStorage.exportBackup()">📥 Exportar</button><button class="btn btn-secondary" onclick="document.getElementById('import-file-input').click()">📤 Importar</button><input id="import-file-input" type="file" accept="application/json" style="display:none"></div></div></div>
  <div class="card" style="margin-top:20px"><h3>🏆 Logros (${d.unlockedAchievements.length} / ${ach.length})</h3><div class="grid-cards">${ach.map(x=>{const ok=d.unlockedAchievements.includes(x.id);return `<div class="card" style="opacity:${ok?'1':'.4'}"><div style="font-size:2rem">${esc(x.icon)}</div><strong>${esc(x.name)}</strong><div style="font-size:.8rem;color:var(--text-muted)">${esc(x.description)}</div></div>`}).join('')}</div></div>`;
   c.querySelector('#import-file-input').onchange=e=>importFile(e.target);
   c.querySelector('#edit-account').onclick=()=>openEditor(a);
   c.querySelector('#switch-account').onclick=()=>selectAccount();
   c.querySelector('#logout-account').onclick=()=>window.CyberAccounts.logout();
  }
  function selectAccount(){localStorage.removeItem('cyberlab_active_account_v1');window.CyberAccounts.activeId=null;window.CyberStorage.setActiveAccount(null);const g=document.getElementById('accounts-gate');if(g)g.style.display='flex';window.CyberAccounts.renderSelection();}
  function openEditor(a){const old=document.getElementById('profile-editor-modal');if(old)old.remove();const m=document.createElement('div');m.id='profile-editor-modal';m.className='modal-overlay active';m.innerHTML=`<div class="modal-card"><button class="modal-close" id="close">✕</button><h3>✏️ Editar perfil</h3><label>Nombre</label><input id="name" class="chat-input" maxlength="24" style="width:100%;margin:6px 0 12px" value="${esc(a.username)}"><label>Biografía</label><textarea id="bio" class="chat-input" maxlength="180" rows="3" style="width:100%;margin:6px 0 12px">${esc(a.bio||'')}</textarea><label>Foto</label><input id="avatar" type="file" accept="image/png,image/jpeg,image/webp" style="width:100%;margin:6px 0 16px"><div id="preview"></div><div style="display:flex;justify-content:flex-end;gap:10px"><button id="cancel" class="btn btn-secondary">Cancelar</button><button id="save" class="btn btn-primary">Guardar</button></div></div>`;document.body.appendChild(m);let avatar=a.avatar;m.querySelector('#avatar').onchange=async e=>{if(e.target.files[0]){avatar=await window.CyberAccounts.compressImage(e.target.files[0]);m.querySelector('#preview').innerHTML=`<img src="${avatar}" style="width:84px;height:84px;object-fit:cover;border-radius:50%;margin-bottom:12px">`;}};m.querySelector('#close').onclick=m.querySelector('#cancel').onclick=()=>m.remove();m.querySelector('#save').onclick=()=>{const name=m.querySelector('#name').value.trim();if(!name)return alert('Escribe un nombre.');if(window.CyberAccounts.accounts.some(x=>x.id!==a.id&&x.username.toLowerCase()===name.toLowerCase()))return alert('Ese nombre ya está usado.');window.CyberAccounts.updateActiveProfile({username:name,bio:m.querySelector('#bio').value,avatar});m.remove();render();};}
  if(window.CyberApp)window.CyberApp.renderProfile=render;
  window.addEventListener('cyberlab_account_changed',()=>setTimeout(render,0));window.addEventListener('cyberlab_state_updated',()=>setTimeout(render,0));setTimeout(render,0);
})();
