/* CyberLab LocalStorage & Cloud State Manager — isolated per account + validated backups */
const STORAGE_PREFIX='cyberlab_user_data_v3_';
const LEGACY_KEYS=['cyberlab_user_data_v2','cyberlab_user_data_v1'];
const REVIEW_INTERVALS=[1,3,7,14,30];
const DEFAULT_STATE={xp:0,level:1,streak:1,lastActiveDate:new Date().toISOString().split('T')[0],hoursStudied:0,masteryLevels:{},completedModules:[],passedQuizzes:[],completedLabs:[],completedChallenges:[],notes:[],mistakes:[],resourceRatings:{},viewedResources:[],unlockedAchievements:[],quizAttempts:{},goals:{dailyMinutes:30,dailyCompleted:false,weeklyModules:2,weeklyCompleted:false},primaryObjective:'Convertirme en profesional de ciberseguridad.',secondaryObjective:'Especializarme en Blue Team & SOC.',onboardingCompleted:false,userLevelPref:'zero'};
function cloneDefaultState(){return JSON.parse(JSON.stringify(DEFAULT_STATE));}
function isObject(v){return v!==null&&typeof v==='object'&&!Array.isArray(v);}
function asArray(v){return Array.isArray(v)?v:[];}
function asNumber(v,f){return Number.isFinite(Number(v))?Number(v):f;}
function sanitizeState(input){const d=cloneDefaultState();if(!isObject(input))return d;d.xp=Math.max(0,asNumber(input.xp,0));d.level=Math.max(1,Math.floor(asNumber(input.level,1)));d.streak=Math.max(1,Math.floor(asNumber(input.streak,1)));d.lastActiveDate=typeof input.lastActiveDate==='string'?input.lastActiveDate:d.lastActiveDate;d.hoursStudied=Math.max(0,asNumber(input.hoursStudied,0));d.masteryLevels=isObject(input.masteryLevels)?input.masteryLevels:{};['completedModules','passedQuizzes','completedLabs','completedChallenges','notes','mistakes','unlockedAchievements','viewedResources'].forEach(k=>d[k]=asArray(input[k]));d.resourceRatings=isObject(input.resourceRatings)?input.resourceRatings:{};d.quizAttempts=isObject(input.quizAttempts)?input.quizAttempts:{};d.goals=isObject(input.goals)?{...d.goals,...input.goals}:d.goals;if(typeof input.primaryObjective==='string')d.primaryObjective=input.primaryObjective.slice(0,500);if(typeof input.secondaryObjective==='string')d.secondaryObjective=input.secondaryObjective.slice(0,500);d.onboardingCompleted=Boolean(input.onboardingCompleted);if(typeof input.userLevelPref==='string')d.userLevelPref=input.userLevelPref;return d;}
class StorageManager{
 constructor(){this.activeAccountId=null;this.data=cloneDefaultState();}
 key(id=this.activeAccountId){return id?`${STORAGE_PREFIX}${id}`:null;}
 setActiveAccount(id){this.activeAccountId=id;if(!id){this.data=cloneDefaultState();return;}this.data=this.loadForAccount(id);this.checkStreak();window.dispatchEvent(new CustomEvent('cyberlab_state_updated',{detail:this.data}));}
 loadForAccount(id){try{const key=this.key(id);let stored=key?localStorage.getItem(key):null;if(!stored){const accounts=window.CyberAccounts?.accounts||[];if(accounts.length===1&&accounts[0]?.id===id){for(const legacyKey of LEGACY_KEYS){const legacy=localStorage.getItem(legacyKey);if(legacy){stored=legacy;localStorage.removeItem(legacyKey);break;}}}}let source=cloneDefaultState();if(stored){const parsed=JSON.parse(stored);source=isObject(parsed)&&isObject(parsed.data)?parsed.data:parsed;}const data=sanitizeState(source);localStorage.setItem(key,JSON.stringify(data));return data;}catch(e){console.error('Error al cargar el perfil:',e);return cloneDefaultState();}}
 saveData(data=this.data,emit=true){this.data=sanitizeState(data);try{if(!this.activeAccountId)throw new Error('No hay cuenta activa');localStorage.setItem(this.key(),JSON.stringify(this.data));}catch(e){console.error('Error al guardar:',e);}if(emit)window.dispatchEvent(new CustomEvent('cyberlab_state_updated',{detail:this.data}));if(window.CyberAccounts?.syncCloudProgress)window.CyberAccounts.syncCloudProgress();}
 importCloudProgress(cloudData){if(!isObject(cloudData))return;const clean=sanitizeState(cloudData);this.saveData(clean);console.log('Progreso de la nube sincronizado en local');}
 checkStreak(){if(!this.activeAccountId)return;const today=new Date().toISOString().split('T')[0],last=this.data.lastActiveDate;if(!last||last===today)return;const diff=Math.round((Date.parse(today)-Date.parse(last))/86400000);this.data.streak=diff===1?this.data.streak+1:1;this.data.lastActiveDate=today;this.saveData();}
 exportBackup(){const account=window.CyberAccounts?.getActive(),payload={schemaVersion:3,exportedAt:new Date().toISOString(),username:account?.username||'Usuario',data:this.data},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`cyberlab_${account?.username||'usuario'}_${new Date().toISOString().split('T')[0]}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
 importBackup(text){try{const parsed=JSON.parse(text),candidate=isObject(parsed)&&isObject(parsed.data)?parsed.data:parsed;if(!isObject(candidate))throw new Error('Formato inválido');this.saveData(sanitizeState(candidate));alert('¡Progreso importado y validado con éxito!');window.location.reload();}catch(e){console.error(e);alert('La copia no es válida o está dañada.');}}
 resetAllData(){if(confirm('¿Reiniciar todo el progreso de este usuario?')){if(this.activeAccountId)localStorage.removeItem(this.key());window.location.reload();}}
}
window.CyberStorage=new StorageManager();window.CyberLabReviewIntervals=REVIEW_INTERVALS;
